# The TriggerTemplate connects the parameters defined in the TriggerBinding with a PipelineRun.
# The PipelineRun is defined within a resourcetemplates such that an instance of a PipelineRun is created 
# at execution time from the TriggerTemplate with the specific parameters from the TriggerBinding.
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
 name: dusbot-triggertemplate-pr
spec:
 params: # incoming parameters from the TriggerBinding
 - name: git-pr-revision
 - name: git-pr-comments-url
 - name: git-pr-author
 - name: git-pr-clone-url
 - name: git-html-url
 resourcetemplates:
 - apiVersion: tekton.dev/v1beta1
   kind: PipelineRun
   metadata:
     # We want the status of the PipelineRun to be published to the GitHub pull requests.
     # This is done via the https://github.com/tektoncd/experimental/tree/master/commit-status-tracker as well as a GitHub account acting as a Bot.
     annotations:
       "tekton.dev/git-status": "true"
       "tekton.dev/status-context": "test-pull-request"
       "tekton.dev/status-description": "DUSBot test pipeline"
       "tekton.dev/status-target-url": "https://console-openshift-console.apps.ocp01.redhat.works/k8s/ns/dusbot-dev/tekton.dev~v1beta1~PipelineRun/test-pull-request-run-$(uid)"
     generateName: test-pull-request-run-
     name: test-pull-request-run-$(uid) # we want unique names for PipelineRun objects
   spec:
     pipelineRef:
       name: test-pull-request
     params:
       - name: git-pr-clone-url
         value: $(tt.params.git-pr-clone-url)
       - name: git-pr-revision
         value: $(tt.params.git-pr-revision)
       - name: git-pr-comments-url
         value: $(tt.params.git-pr-comments-url)
       - name: git-html-url
         value: $(body.repository.html_url)
       - name: git-pr-author
         value: $(tt.params.git-pr-author)
       - name: image-action-server
         value: image-registry.openshift-image-registry.svc:5000/dusbot-dev/action-server
       - name: image-dusbot
         value: image-registry.openshift-image-registry.svc:5000/dusbot-dev/dusbot
     resources:
     - name: source
       resourceSpec:
         type: git
         params:
           - name: revision
             value: $(tt.params.git-pr-revision)
           - name: url
             value: $(tt.params.git-html-url)
     serviceAccountName: github-tekton-sa
     timeout: 0h15m0s
     workspaces:
     - name: shared-pr-workspace
       persistentvolumeclaim:
         claimName: test-pr-volume
